name: Portfolio CI/CD

on:
  push:
    branches:
      - main
      - 'feature/**'

permissions:
  contents: write
  deployments: write
  statuses: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Build project
        run: npm run build --legacy-peer-deps

      - name: Prepare distribution files
        run: |
          mkdir -p dist
          # Only copy files tracked by Git
          git ls-files | while read file; do
            mkdir -p "dist/$(dirname "$file")"
            cp "$file" "dist/$file"
          done
          echo "Files copied to dist (respecting .gitignore):"
          ls -la dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          name: github-pages

  deploy-feature:
    needs: build
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    environment:
      name: github-pages-staging
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: List distribution contents
        run: ls -la ./dist

      - name: Extract artifact
        run: |
          tar -xvf ./dist/artifact.tar -C ./dist
          ls -la ./dist

      - name: Verify deployment settings
        run: |
          echo "Verifying Netlify Configuration..."
          echo "Current branch: ${{ github.ref }}"
          ls -la ./dist

      - name: Deploy to Netlify (Staging)
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          deploy-message: "Deploy from GitHub Actions (Feature Branch)"
          enable-pull-request-comment: true
          enable-commit-comment: true
          alias: preview-${{ github.sha }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  deploy-production:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: Extract artifact
        run: |
          tar -xvf ./dist/artifact.tar -C ./dist
          ls -la ./dist

      - name: Deploy to Netlify (Production)
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          deploy-message: "Deploy from GitHub Actions (Production)"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Output deployment URL
        run: echo "Production URL - ${GITHUB_PAGES_URL}"
        env:
          GITHUB_PAGES_URL: ${{ steps.deployment.outputs.page_url }}