name: Portfolio CI/CD

on:
  push:
    branches:
      - main
      - feature/**

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Build project
        run: npm run build --legacy-peer-deps

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist  # Usamos 'dist' porque es la carpeta que genera tu comando build

  deploy-feature:
    needs: build
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    environment:
      name: github-pages-staging
    steps:
      - name: Move files to staging subfolder
        run: |
          mkdir -p staging
          cp -r dist/* staging/  # Copiamos los archivos de 'dist' a 'staging'
      - name: Deploy to GitHub Pages (Staging)
        uses: actions/deploy-pages@v4
      - name: Output deployment URL
        run: echo "Staging URL - https://${{ github.repository_owner }}.github.io/${{ github.repository }}/staging"

  deploy-production:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Move files to production subfolder
        run: |
          mkdir -p prod
          cp -r dist/* prod/  # Copiamos los archivos de 'dist' a 'prod'
      - name: Deploy to GitHub Pages (Production)
        uses: actions/deploy-pages@v4
      - name: Output deployment URL
        run: echo "Production URL - https://${{ github.repository_owner }}.github.io/${{ github.repository }}/prod"